services:
  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  auth-service: &auth-service
    build:
      context: ./auth-service
      dockerfile: ./auth-service.dockerfile
    restart: always
    volumes: [ "./auth-service:/auth-service" ]
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  auth-service-dev:
    <<: *auth-service
    build:
      context: ./auth-service
      dockerfile: ./auth-service.dev.dockerfile

  broker-service: &broker-service
    build:
      context: ./broker-service
      dockerfile: ./broker-service.dockerfile
    restart: always
    volumes: [ "./broker-service:/broker-service" ]
    depends_on:
      - auth-service
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  broker-service-dev:
    <<: *broker-service
    depends_on:
      - auth-service-dev
