services:

  # This will be used by the auth-service
  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  # auth-service 
  auth-service: &auth-service
    build:
      context: ./auth-service
      dockerfile: ./auth-service.dockerfile
    restart: always
    volumes: [ "./auth-service:/auth-service" ]
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  # for dev purpose 
  auth-service-dev:
    <<: *auth-service
    build:
      context: ./auth-service
      dockerfile: ./auth-service.dev.dockerfile
    volumes:
      - "./auth-service:/app"

  # broker-service
  # TODO: Add a env variable for auth-service
  broker-service: &broker-service
    build:
      context: ./broker-service
      dockerfile: ./broker-service.dockerfile
    restart: always
    volumes: [ "./broker-service:/broker-service" ]
    depends_on:
      - auth-service
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  # for dev purpose
  broker-service-dev:
    <<: *broker-service
    build:
      context: ./broker-service
      dockerfile: ./broker-service.dev.dockerfile
    depends_on:
      - auth-service-dev
    volumes:
      - "./broker-service:/app"

  logger-service: &logger-service
    build:
      context: ./logger-service
      dockerfile: ./logger-service.dockerfile
    restart: always
    volumes: [ "./logger-service:/logger-service" ]
    depends_on:
      - mongo
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1

    # for dev purpose
  logger-service-dev:
    <<: *logger-service
    build:
      context: ./logger-service
      dockerfile: ./logger-service.dev.dockerfile
    depends_on:
      - mongo
    volumes:
      - "./logger-service:/app"

  mongo:
    image: "mongo:4.2.16-bionic"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=logs
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./db-data/mongo/:/data/db
